### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aditya-rajput200**
[BUGFIX]: their is two times of appbar calling at diffrent place . i have enhance the responcive degin and ajust the etherum img as per the screen

---

# Pull Request Title

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Number:** Fixes # (issue number)

## 🛠️ Type of Change

- [x] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.
- [x] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [x] **Documentation:** I’ve updated the documentation to reflect my changes.
- [x] **Warnings:** My changes introduce no new warnings.
- [x] **Tests:** I’ve added tests to verify that my changes work as expected.
- [x] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Review by Aditya-rajput200 — COMMENTED** [review]
Enhance the Ui of the home Page .

**Review by ghost — CHANGES_REQUESTED** [review]
You are changing appbar and hero file so why are you writing update readme on title ??
What have you solved ? Kindly provide a video and change the pr title
Thanks

**Review by Aditya-rajput200 — COMMENTED** [review]
sorry for that

**Comment by cb7chaitanya** [comment]
Sorry, the Pull request message isn't indicative of what you did at all @Aditya-rajput200 
Neither have you provided any context for what you have actually done, please provide screenshots for UI elements

I am closing this PR for now

**Pull request closed without merging**
