### PR TITLE
[ENH]: Added Prettier for Code Formatting

### LINKED ISSUE #34: Add Prettier
Summary
Add Prettier to the project to ensure consistent code formatting across all files and improve code readability.

Current Behavior
Currently, the project lacks a standardized code formatting tool, leading to inconsistent code styles.

Expected Behavior
Prettier should be integrated into the project, and a configuration file should be added to define the formatting rules. This will ensure consistent code formatting throughout the project.

### PR DESCRIPTION
**Pull request by Riya267**
---

# Add Prettier for Code Formatting

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Number:** Fixes #34 

## 🛠️ Type of Change

- [ ] 🐛 Bug fix
- [x] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.
- [x] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [x] **Documentation:** I’ve updated the documentation to reflect my changes.
- [x] **Warnings:** My changes introduce no new warnings.
- [x] **Tests:** I’ve added tests to verify that my changes work as expected.
- [x] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

## Changes
Added Prettier Configuration:

.prettierrc: Added for consistent code styling.
package.json: Included Prettier scripts for formatting and checking.
package-lock.json: Updated to reflect the addition of Prettier.
Formatted Codebase: Applied Prettier formatting to existing files to ensure consistency.

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
i have added a pr of eslint so in future if we use eslint will prettier override eslint??
if doesnt do can you add that ? @Riya267

**Comment by Riya267** [comment]
> i have added a pr of eslint so in future if we use eslint will prettier override eslint?? if doesnt do can you add that ? @Riya267

Yes, Prettier and ESLint can sometimes conflict depending on the rules and plugins you use. To prevent conflicts and ensure consistent formatting, you should integrate Prettier as a plugin in your ESLint configuration. This setup ensures that Prettier and ESLint complement each other effectively.

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@Riya267 thanks

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@Riya267 my eslint pr has been merged
as i can see you pr is conflicting too much so please kindly close this pr and re do the work and later open a new pr

**Comment by Riya267** [comment]
> @Riya267 my eslint pr has been merged as i can see you pr is conflicting too much so please kindly close this pr and re do the work and later open a new pr

no need for new pr as conflicts are resolved now

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@Riya267 is prettier over writing eslint..have you tested ?

**Comment by Riya267** [comment]
no its over writing

**Pull request merged**
