### PR TITLE
solved the appbar alignment and added the wallet button when the use …

### LINKED ISSUE #111: [BUGFIX] Appbar alignment is bugging when clicking on user image when logged in, also add a button with wallet icon to direct users to the wallet page
[screen-capture.webm](https://github.com/user-attachments/assets/f442f334-06a8-48db-84a3-b0f300ebc36d)

-Take an updated pull of the dev-frontend branch and commit your changes there after fix

### PR DESCRIPTION
**Pull request by Ameerjafar**
# Pull Request Title

https://github.com/user-attachments/assets/35328487-f640-4bce-b316-0648c4a01c12

I have added the user profile in the wallet page as well

Screenshot 2024-08-14 200143

**Issue Number:** Fixes #111 

## 🛠️ Type of Change

- [ ✅ ] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [ ✅] **Code Style:** My code adheres to the project’s style guidelines.
- [✅ ] **Self-Review:** I have reviewed my own code and made improvements.
- [✅ ] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [] **Documentation:** I’ve updated the documentation to reflect my changes.
- [✅ ] **Warnings:** My changes introduce no new warnings.
- [✅ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [✅ ] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Comment by Ameerjafar** [comment]
@cb7chaitanya can you kindly check the pr.

**Review by Rudra-Sankha-Sinhamahapatra — COMMENTED** [review]
Looks fine man 
Good work

**Review by Rudra-Sankha-Sinhamahapatra — COMMENTED** [review]
Can you share a screenshot or a video ?

**Comment by Ameerjafar** [comment]
it has resolved @Rudra-Sankha-Sinhamahapatra

**Comment by Ameerjafar** [comment]
@cb7chaitanya can you create some other issue to work.

**Comment by Ameerjafar** [comment]
@cb7chaitanya @axatbhardwaj can you create more issue to work it on

**Pull request merged**
