### PR TITLE
[ENH}: Nextjs top loader

### PR DESCRIPTION
**Pull request by vanshavenger**
---

# Pull Request Title

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Number:** Fixes # (issue number)

## 🛠️ Type of Change

- [ ] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.
- [ ] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [x] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [ ] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Review by Rudra-Sankha-Sinhamahapatra — CHANGES_REQUESTED** [review]
You have branch merge conflicts fix them

**Comment by vanshavenger** [comment]
Hey @Rudra-Sankha-Sinhamahapatra done!

**Comment by cb7chaitanya** [comment]
Add Screenshots or Video links for bits you change in the UI

**Comment by vanshavenger** [comment]
@cb7chaitanya ne change is we get a smaller loader when we move from route to another or when a request is being sent, other is when we scroll down we a scroll to top button

**Comment by vanshavenger** [comment]
Screenshot 2024-08-06 at 1 02 31 AM

**Comment by vanshavenger** [comment]
Any  further chnages required?

**Comment by vanshavenger** [comment]
@Rudra-Sankha-Sinhamahapatra, @cb7chaitanya  i fixed one lint error of Image in this too, UseEffect one looking into that, kindly suggest further changes if required?

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Vai maybe I have solved the eslint warning of img tag 
My pr has been merged kindly please sync your branch and then see if is reproducing any issues or not 
Thanks for your contribution

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
And it will be good if you test prettier and eslint locally and provide screenshots and videos it will be good
Ensure the prettier must override the eslint configurations with no eslint errors or warnings

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@vanshavenger

**Comment by vanshavenger** [comment]
@Rudra-Sankha-Sinhamahapatra  @cb7chaitanya  Done Guys! :)))

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Please provide screenshots that your pr doesn't create any linting warnings

**Comment by vanshavenger** [comment]
Screenshot 2024-08-06 at 3 23 17 AM

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@vanshavenger bhai also give those pR that what kind of ui change you made

**Comment by vanshavenger** [comment]
@Rudra-Sankha-Sinhamahapatra bhai Alreeady mentioned it in the comments and attached screenshot for scroll to the top too.

**Pull request merged**
