### PR TITLE
Fix : Make the wallet page dynamic

### LINKED ISSUE #126: [FIX] Make the wallet page dynamic using the fresh wallet service created
- Take an updated pull from dev branch
- Make your PR to the dev branch

### PR DESCRIPTION
**Pull request by saketsingh0078**
#  Fix : Make the wallet page dynamic
- The total balance is fetch dynamically 
-  some fix in walletService 
-  fix some css issue like in the leftsideBar  icons are not center
-  In the topBar search bar give some padding

**Issue Number:** Fixes #126 

## 🛠️ Type of Change

- [x] 🐛 Bug fix
- [x] 🚨 Breaking change

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Can you provide screenshots or screen recordings

**Comment by saketsingh0078** [comment]
@rushhaaland 
https://github.com/user-attachments/assets/f11ea4b6-9466-4556-befe-bbd8129dc236

**Review by ghost — COMMENTED** [review]
@saketsingh0078 we can already see the profile icon there in the page ,can you elaborate your changes

**Comment by cb7chaitanya** [comment]
This does work @saketsingh0078 but can you please use better data fetching practices here in Next rather than using useEffect, maybe use asynchronous components in Next

**Comment by saketsingh0078** [comment]
ok sure @cb7chaitanya

**Comment by saketsingh0078** [comment]
@cb7chaitanya make the changes, Please let me know if more to change.

**Comment by cb7chaitanya** [comment]
@saketsingh0078 Do the updated changes work? 
Can you send me a screen recording for the same

**Comment by saketsingh0078** [comment]
@cb7chaitanya  Yes, I make the changes .

https://github.com/user-attachments/assets/62383d7d-2370-4cc2-977a-18ae5018aed5

**Comment by ghost** [comment]
@saketsingh0078 in this video you are showing code you dont need to show this,You please show the things you have done in the site
You can explain with video
Thanks for your contribution

**Comment by cb7chaitanya** [comment]
Merging it, good work @saketsingh0078

**Pull request merged**
