### PR TITLE
Added the Alert Dialog for Signout

### PR DESCRIPTION
**Pull request by pruthviraj7714**
**Added A Alert Dialog for Signout**

Preview : https://github.com/user-attachments/assets/bbf23871-20ec-4920-85ec-5c7fa59610df

## 🛠️ Type of Change
- [ ] 🐛 Bug fix
- [✅] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [✅] **Code Style:** My code adheres to the project’s style guidelines.
- [✅ ] **Self-Review:** I have reviewed my own code and made improvements.
- [✅] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [✅] **Documentation:** I’ve updated the documentation to reflect my changes.
- [✅] **Warnings:** My changes introduce no new warnings.
- [✅] **Tests:** I’ve added tests to verify that my changes work as expected.
- [✅] **Passes Locally:** All new and existing unit tests pass on my local machine.

### CODE REVIEW

**Comment by pruthviraj7714** [comment]
@cb7chaitanya

**Comment by cb7chaitanya** [comment]
Why have you added a pnpm lock file? @pruthviraj7714

**Comment by pruthviraj7714** [comment]
@cb7chaitanya removed it

**Comment by pruthviraj7714** [comment]
@cb7chaitanya can I create a new PR for this

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Your Lint checks have been failed 
And why did you push so many commits of others?
You can close this pr and later you can create a fresh pr if this feature is required

thanks for your contribution 
@pruthviraj7714

**Pull request closed without merging**
