### PR TITLE
fix-home-page-ui-bug

### LINKED ISSUE #145: [BUGFIX] Fix this small UI bug
- This is the bug 
Focus on the logo
Screenshot (93)
Screenshot (94)
- The dropdown should be overlapping the logo

### PR DESCRIPTION
**Pull request by saketsingh0078**
**Issue Number:** Fixes #145 

## 🛠️ Type of Change

- [x] 🐛 Bug fix

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.

https://github.com/user-attachments/assets/37d84445-b65a-4e28-98c4-8bc1410886bb

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Looks good. Thanks for your contribution @saketsingh0078

**Comment by cb7chaitanya** [comment]
Clicking on the profile image button, disrupts the alignment of the appbar, this was an issue that was fixed prior to the current issue, I would appreciate if you can identify and remove that issue from your code

**Comment by saketsingh0078** [comment]
Ok , I try make it correct .

**Comment by saketsingh0078** [comment]
@cb7chaitanya fix the juggling of the  appbar on click.

https://github.com/user-attachments/assets/82ff232d-f644-41ce-a855-b2cf20002c70

**Pull request merged**
