### PR TITLE
Refactor code and add card images

### LINKED ISSUE #23: Improve the UI to our own better version, different from the TipLinks UI.
**This PR aims to enhance our user interface by differentiating it from the TipLinks UI and creating a better version. The changes include:**

- Redesigning the layout for a more user-friendly and mono-chromatic look.
- Updating color schemes.
- Adding new visual elements for improved aesthetics
- Optimizing the interface for better performance and responsiveness

**Changes:**

1. **Layout Improvements:**
    - Redesigned the main layout to be more intuitive and visually appealing.
    - Removed elements that were directly copied from TipLinks.
2. **Color Schemes:**
    - Introduced a new color palette that aligns with our brand identity.
3. **Visual Enhancements:**
    - Added new icons and images to enhance the visual appeal.
    - Improved spacing and alignment for a cleaner appearance.
4. **Performance Optimization:**
    - Refactored CSS and JavaScript for better performance.
    - Ensured that the UI is responsive across different devices and screen sizes.

**Screenshots:**

**Before:**

image

**After:**

image

**Before:**

image

**After:**

image

**Before:**

image

**After:**

image

**Testing:**

- [x]  Verified that the new UI works well on different browsers (Chrome, Firefox, Safari)
- [x]  Tested responsiveness on mobile and tablet devices
- [x]  Confirmed that all existing functionality remains intact

**Additional Notes:**

- Please review the new design and provide feedback. If you are okay with it, I will start making changes according to feedback and complete the UI.

@cb7chaitanya

### PR DESCRIPTION
**Pull request by Pawank06**
---

# Refactor code and add card images

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Number:** Fixes #23 

## 🛠️ Type of Change

- [ ] 🐛 Bug fix
- [x] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## Before:
Screenshot from 2024-08-05 10-18-23

## After:

Screenshot from 2024-08-05 11-14-31

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.
- [ ] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [ ] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [ ] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Review by visioncrunch — APPROVED** [review]
Remove the Images in png, make them webp

**Comment by Pawank06** [comment]
@cb7chaitanya ser please review.

**Comment by cb7chaitanya** [comment]
What all have you changed? Can you add screenshots for all the changes here?

**Comment by Pawank06** [comment]
> What all have you changed? Can you add screenshots for all the changes here?

- First one, as I already mentioned, includes the images.
image

- Changed the lorem text.
image

- Imported footer logos from react-icons.
image

- Added some container width to headings and subheadings.

**Pull request closed without merging**
