### PR TITLE
chore: adding ci/cd and scripts

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
**Adding CI/CD pipelines** 

>- workflows
1. PR lint check workflow
2. stale issues workflow

>- scripts

1. lint, formating, and typechecking scripts.

>- Screenshots 

image

image

image

### CODE REVIEW

**Comment by DhairyaMajmudar** [comment]
Hi @cb7chaitanya I've some basic workflows and scripts do you need me to run the format/lint scripts? or will it be done on your end?

**Comment by cb7chaitanya** [comment]
Please run it @DhairyaMajmudar

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@DhairyaMajmudar please provide screenshots or videos

**Comment by DhairyaMajmudar** [comment]
I've updated PR with screenshots 

cc: @cb7chaitanya @Rudra-Sankha-Sinhamahapatra

**Comment by cb7chaitanya** [comment]
Seems good @DhairyaMajmudar

**Pull request merged**
