### PR TITLE
[FEAT] Create a custom authentication page

### LINKED ISSUE #158: [FEAT] Create a custom authentication page

### PR DESCRIPTION
**Pull request by dhruv-colosus**
---

# [FEAT] Create a custom authentication page

Added a custom signing page at /signin route . On clicking the sign in through google button it redirects to google auth page and after signing up it goes back to landing page

Screenshot 2024-09-13 at 2 54 02 PM

## After Clicking Sign In. (Loading)
Screenshot 2024-09-13 at 3 14 59 PM

**Issue Number:** Fixes #158 

## 🛠️ Type of Change

- [ ] 🐛 Bug fix
- [x] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [ ] **Code Style:** My code adheres to the project’s style guidelines.
- [ ] **Self-Review:** I have reviewed my own code and made improvements.
- [ ] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [ ] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [ ] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Comment by cb7chaitanya** [comment]
Looks super cool @dhruv-colosus 
Do tell me your views @axatbhardwaj @rushhaaland

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Looks fine to me but will we only have this page for dark mode ?

**Comment by dhruv-colosus** [comment]
Hey @rushhaaland  , I have added light mode support to , it will look like this
Screenshot 2024-09-15 at 10 02 44 PM

**Comment by ghost** [comment]
Nice work @dhruv-colosus

**Comment by krey-yon** [comment]
can you make "signup/signin" text in center ?

**Comment by dhruv-colosus** [comment]
> can you make "signup/signin" text in center ?

It doesn't look good that way brother

**Comment by cb7chaitanya** [comment]
Provides a good starting point to iterate over and improve @dhruv-colosus 
Good work

**Pull request merged**
