### PR TITLE
Added the spinner until the session get's the image

### LINKED ISSUE #172: [BUG] Appbar rendering issue
[screen-capture (2).webm](https://github.com/user-attachments/assets/fdd7958a-b6db-47ff-aaef-b28d5c4c8ee8)

Session is picked up after the page fully loads and therefore leading to a delay in the rendering of user image and wallet icon 

- Take an updated pull and make changes to dev

### PR DESCRIPTION
**Pull request by Ameerjafar**
---

# Pull Request Title

https://github.com/user-attachments/assets/89bc1d82-23ad-443b-9ebf-5fe9d4e4f186

**Issue Number:** Fixes #172 

## 🛠️ Type of Change

- [✅] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [✅] **Code Style:** My code adheres to the project’s style guidelines.
- [✅] **Self-Review:** I have reviewed my own code and made improvements.
- [✅] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [✅] **Documentation:** I’ve updated the documentation to reflect my changes.
- [✅] **Warnings:** My changes introduce no new warnings.
- [✅] **Tests:** I’ve added tests to verify that my changes work as expected.
- [✅] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Comment by Ameerjafar** [comment]
@cb7chaitanya if anything i wanted to do in this pr let me know?

**Comment by cb7chaitanya** [comment]
Please provide a screen recording of what you changed

**Comment by Ameerjafar** [comment]
@cb7chaitanya i have added the video

**Comment by cb7chaitanya** [comment]
Skeletons might look better, please try adding skeletons here rather than a spinner @Ameerjafar

**Comment by Ameerjafar** [comment]
@cb7chaitanya working on that.

**Comment by Ameerjafar** [comment]
@cb7chaitanya i have added the skeleton loading and I took the reference from this pr #188  i have the updated the video as well

**Comment by cb7chaitanya** [comment]
Merged it @Ameerjafar

**Pull request merged**
