### PR TITLE
[BUGFIX]: fixed next-auth google sign-in

### LINKED ISSUE #24: Login with Google Button not working
For me "login with Google" button is not working
Someone please comment down below if its working for you,
do comment down and let me know if it is not working also

### PR DESCRIPTION
**Pull request by dyaipayan22**
https://github.com/user-attachments/assets/09fd13ee-e055-402f-a95e-f57071324a84

---

# [BUGFIX]: fixed next-auth google sign-in

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Number:** Fixes #24 

## 🛠️ Type of Change

- [x] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.
- [x] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [ ] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [x] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Comment by cb7chaitanya** [comment]
https://github.com/user-attachments/assets/23a1b646-9f99-4d78-9594-fb14e05d2803

What is not working in this? Can you point that out?

**Comment by Riya267** [comment]
> screen-capture.mp4 
> What is not working in this? Can you point that out?

Hi @cb7chaitanya,

The Google Sign-In feature is already functioning, as mentioned in the previous comment on this issue. It would be best to close this issue if everything is working fine. Contributors can open separate issues for UI concerns or other related issues. Keeping this issue focused will help avoid confusions.

**Comment by dyaipayan22** [comment]
@cb7chaitanya My bad. I should checked. I saw an open issue and aw that you were getting a 403 error so I worked on it.

**Comment by cb7chaitanya** [comment]
> > screen-capture.mp4
> > What is not working in this? Can you point that out?
> 
> Hi @cb7chaitanya,
> 
> The Google Sign-In feature is already functioning, as mentioned in the previous comment on this issue. It would be best to close this issue if everything is working fine. Contributors can open separate issues for UI concerns or other related issues. Keeping this issue focused will help avoid confusions.

Yes, I am closing that issue now

**Comment by cb7chaitanya** [comment]
> @cb7chaitanya My bad. I should have checked. I saw an open issue and that you were getting a 403 error so I worked on it.

No worries at all, i should have closed that, as I fixed that and pushed the fix afterwards

**Pull request closed without merging**
