### PR TITLE
added dark mode

### PR DESCRIPTION
**Pull request by ArpitBlagan**
Screenshot 2024-08-02 at 12 44 38 PM

Screenshot 2024-08-02 at 12 44 35 PM

### CODE REVIEW

**Comment by Praashh** [comment]
do we need ?  #1 can you please check it.

**Comment by HashirAKB** [comment]
@ArpitBlagan Having some difficulties setting up this project in local with docker. How can we connect?

**Comment by ArpitBlagan** [comment]
> @ArpitBlagan Having some difficulties setting up this project in local with docker. How can we connect?
we dont' need the RUN npm run dev line in docker file and change the cmd to ["npm","run","dev"]

**Comment by ArpitBlagan** [comment]
> do we need ? #1 can you please check it.

I personally prefer dark mode but your's look great

**Comment by cb7chaitanya** [comment]
@ArpitBlagan I don't think this is needed + UI has to be similar to what @Praashh has created in #1

**Comment by ArpitBlagan** [comment]
> @ArpitBlagan I don't think this is needed + UI has to be similar to what @Praashh has created in #1

okay no problem

**Pull request closed without merging**
