### PR TITLE
[ENH]: add scroll to top button

### PR DESCRIPTION
**Pull request by vanshavenger**
---

# Pull Request Title

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Number:** Fixes # (issue number)

## 🛠️ Type of Change

- [ ] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [ ] **Code Style:** My code adheres to the project’s style guidelines.
- [ ] **Self-Review:** I have reviewed my own code and made improvements.
- [ ] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [ ] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [ ] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Comment by cb7chaitanya** [comment]
You have added the scroll to top button in the root layout file, just add it to the landing page for now, that should be enough

**Comment by vanshavenger** [comment]
@cb7chaitanya  i did that as it can be used for eah page later in future?
So still i move it on landing page?

**Comment by cb7chaitanya** [comment]
Yes please just keep it on landing page, if needed we can shift it to layout file later

**Comment by vanshavenger** [comment]
@cb7chaitanya  moved it in the nextJs toploader branch and resolved all linting issues there.

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Bhai your linting checks has been failed as I can see now 
I have already fixed the linting warnings and issues 
Please don't remove them

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@vanshavenger

**Comment by vanshavenger** [comment]
@Rudra-Sankha-Sinhamahapatra i uodated the other PR , in that i have fixed it , and the CI pipeline also did the linting checks, kindly refer that PR

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Yeah your other pr looks good 
So if this pr is not going to do anything close this 
And provide screenshots for the changes you made on the other pr

**Comment by vanshavenger** [comment]
Already did that shared the ss, will close this PR once chaitanya reviews the other one :)))🚀

**Comment by cb7chaitanya** [comment]
Checks have failed @vanshavenger

**Comment by vanshavenger** [comment]
Hey  this is already merged with my other PR in which everything was correct. 
Thanks closing this one.

**Comment by cb7chaitanya** [comment]
Cool

**Pull request closed without merging**
