### PR TITLE
[fix] Signup with google button on Hero page was not working

### PR DESCRIPTION
**Pull request by ankitmrmishra**
---

# Pull Request Title

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Number:** Fixes # (issue number)

## 🛠️ Type of Change

- [x] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.
- [ ] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [ ] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [ ] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Comment by ankitmrmishra** [comment]
@cb7chaitanya sir, please review the PR, thank you.

**Comment by cb7chaitanya** [comment]
@ankitmrmishra give me a video showing that it's working, and have you made the hero section a client component?

**Comment by ankitmrmishra** [comment]
@cb7chaitanya here's the video and I haven't made Hero section a client component.


https://github.com/user-attachments/assets/a01a036c-bc29-4318-ad1f-a321244b2430

**Comment by ankitmrmishra** [comment]
@cb7chaitanya any update on this.

**Comment by Ameerjafar** [comment]
your branch has conflicts @ankitmrmishra

**Pull request closed without merging**
