### PR TITLE
#146: Fix the Wallet page user Icon to be same as the Home page usericon dropdown

### LINKED ISSUE #146: [BUGFIX] Fix this
Screenshot (95)

- This should be the same as the dropdown on the landing page, please fix this

### PR DESCRIPTION
**Pull request by Saurav1509**
# Fixes #146 bug: Wallet Page user Icon dropdown

**Issue Number:** Fixes #146 

## 🛠️ Type of Change

- [x] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

This fixes the Wallet Page User Icon to be the same dropdown as the HomePage user Icon.
image

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.

---

### CODE REVIEW

**Comment by Saurav1509** [comment]
Additional - This also fixes the Tiplink icon on the top left to be same as the Home page one. the current one is a little bonked.

**Comment by cb7chaitanya** [comment]
Does the UI get bonked on reload on your end? If not, please do send a video testing it out for reload

**Comment by Saurav1509** [comment]
Sorry for the bad wording, 
No major issue, its just that the tiplink logo on the wallet page is slightly different(seems wrong) than the tiplink logo on the Home page,

below is the difference,

Wallet Page
image

Main Home Page
image

no issues while reloading,

https://github.com/user-attachments/assets/358cacab-7a37-4863-a0bb-94d877050d68

**Comment by Saurav1509** [comment]
@cb7chaitanya requesting review

**Comment by cb7chaitanya** [comment]
The search bar gets displaced and this has been fixed in another PR using skeletons so closing this

**Pull request closed without merging**
