### PR TITLE
Added the basic ui for the wallet page(send, addfunds)

### LINKED ISSUE #12: create the wallet page in the user profile.
currently we don't have user wallet page(frontend).

### PR DESCRIPTION
**Pull request by Ameerjafar**
---

# Pull Request Title

I have created the basic for the wallet page(send, setAddFunds, withdraw) 

https://github.com/user-attachments/assets/7bbb2e09-cbd4-4a21-a4f9-01f0e28b3832

**Issue Number:** Fixes #12

### CODE REVIEW

**Comment by Ameerjafar** [comment]
@cb7chaitanya can you kindly review the pr.

**Comment by cb7chaitanya** [comment]
Why create a seperate footere specifically in the wallet page? @Ameerjafar

**Comment by Ameerjafar** [comment]
we have different appabar and wallet page once the user is logged into the website in the actual tiplink project @cb7chaitanya

**Comment by Ameerjafar** [comment]
@cb7chaitanya  i have removed the Walletappbar  component  i Just use the existing appbar Component only. but footer is diff when you logged into tiplink website.

**Comment by Ameerjafar** [comment]
@cb7chaitanya can you check now I have removed the footer and the appbar.

**Comment by cb7chaitanya** [comment]
The UI has changed, do you want to work on updating your code to fit that UI?

**Comment by Ameerjafar** [comment]
@cb7chaitanya yes i want to work on that please tell me.

**Comment by Ameerjafar** [comment]
@cb7chaitanya can you give the ui so i can work on.

**Comment by cb7chaitanya** [comment]
@Ameerjafar Take an updated Pull, see the current landing page to get an idea
Here you go, the initial proposed change 
https://github.com/code100x/tiplink/issues/23#issue-2446581822

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@Ameerjafar are you working on this ? so fix the conflicts and update it

**Comment by Ameerjafar** [comment]
Working on it

**Pull request closed without merging**
