### PR TITLE
dark mode

### LINKED ISSUE #170: [FEAT] Configure dark mode for the project
- Configure dark mode in project
- Bear in mind every component/page that is there on the project, you have to make a dark mode for

### LINKED ISSUE #183: [ENHANCEMENT] Create a new Figma File for tiplink
- Create a figma file for new UI of Tiplink
- Read Disclaimer before doing anything with the project

### PR DESCRIPTION
**Pull request by that-avg-dev**
# Complete Dark Mode 

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Numbers:** Fixes #183, Fixes #170 

## 🛠️ Type of Change

- [ ] 🐛 Bug fix
- [x] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.
- [x] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [ ] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [x] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Comment by cb7chaitanya** [comment]
Add Screenshots here or a video showcasing what you changed @kairveeehh

**Comment by that-avg-dev** [comment]
[dark.pdf](https://github.com/user-attachments/files/17249593/dark.pdf)
[light.pdf](https://github.com/user-attachments/files/17249594/light.pdf)


@cb7chaitanya  attached the screenshots

**Comment by cb7chaitanya** [comment]
The marquee is looking odd in dark mode, rest of it looks fine

**Comment by that-avg-dev** [comment]
> The marquee is looking odd in dark mode, rest of it looks fine 

Sure I'll try making it better any suggestions are welcomed.

**Comment by that-avg-dev** [comment]
@cb7chaitanya  you mean this part right?
Screenshot 2024-10-05 150910

**Comment by cb7chaitanya** [comment]
Yes @kairveeehh 
In the dark background, this is looking odd

**Comment by cb7chaitanya** [comment]
@kairveeehh Resolve conflicts

**Comment by that-avg-dev** [comment]
Yes sir , by tonight I'll

**Pull request closed without merging**
