### PR TITLE
[BUGFIX]: Prevent unauthorised user to access protected routes

### PR DESCRIPTION
**Pull request by aloksharma10**
---

# Pull Request Title

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Number:** Fixes # (issue number)

## 🛠️ Type of Change

- [x] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.
- [x] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [x] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [ ] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@aloksharma10 can you provide a video

**Comment by aloksharma10** [comment]
> @aloksharma10 can you provide a video

Sure,

Here is the video: 

https://github.com/user-attachments/assets/9bfb5ff2-3c2c-4fcd-9c8e-d6267efebf3e

**Comment by dyaipayan22** [comment]
@aloksharma10  Not a good convention to have **protected** in the url. Modify with an alternative

**Comment by cb7chaitanya** [comment]
Great but why push the protected page here, if it was only meant for testing? @aloksharma10

**Comment by aloksharma10** [comment]
> Great but why push the protected page here, if it was only meant for testing? @aloksharma10

The reason behind this is that I wrapped the protected page into the group routing so that, eventually, when more protected pages are added, all pages will be in that protected page group route.

If you feel I should remove this, please let me know, and I'll remove it immediately.

**Comment by cb7chaitanya** [comment]
Remove it from now, would merge it then @aloksharma10

**Comment by aloksharma10** [comment]
> Remove it from now, would merge it then @aloksharma10

Removed, Please review it once.

**Comment by cb7chaitanya** [comment]
Cool, merging it @aloksharma10

**Pull request merged**
