### PR TITLE
Added the Wallet page

### LINKED ISSUE #12: create the wallet page in the user profile.
currently we don't have user wallet page(frontend).

### LINKED ISSUE #98: Implement User Wallet Page.
### **Title**: Create User Wallet Page

**Description**:
- Implement the User Wallet page in the application.
- Ensure that the design and layout follow the provided Figma design.

**Tasks**:
1. Create the User Wallet page.
2. Implement UI components based on the design.
3. Ensure responsiveness and cross-browser compatibility.

**Demo**: 

MacBook Air - 1(9)

**Acceptance Criteria**:
- The User Wallet page is functional and visually aligns with the design.
- The page is fully responsive.

**Priority**: Medium/High

**Assignee**: I'm working on it.

### PR DESCRIPTION
**Pull request by Ameerjafar**
---

# Pull Request Title

I have added the wallet page

https://github.com/user-attachments/assets/a8da5760-9f18-4e68-8d74-1a6eb5236e1d

**Issue Number:** Fixes #98  && Fixes #12
 

## 🛠️ Type of Change

- [ ] 🐛 Bug fix
- [ ✅ ] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [✅ ] **Code Style:** My code adheres to the project’s style guidelines.
- [✅ ] **Self-Review:** I have reviewed my own code and made improvements.
- [ ✅] **Warnings:** My changes introduce no new warnings.
- [ ✅] **Tests:** I’ve added tests to verify that my changes work as expected.
- [✅ ] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Comment by Ameerjafar** [comment]
@cb7chaitanya can you kindly review the pr

**Comment by cb7chaitanya** [comment]
Linting checks have failed + why place the left/right/top components within the wallet folder and not in the components folder @Ameerjafar

**Comment by Ameerjafar** [comment]
@cb7chaitanya can you review the code now.

**Comment by cb7chaitanya** [comment]
Good work, merging it @Ameerjafar

**Comment by Ameerjafar** [comment]
@cb7chaitanya can you create some issue to work it on.

**Comment by cb7chaitanya** [comment]
@Ameerjafar Yes I will be adding more issues in some time

**Pull request merged**
