### PR TITLE
Theme toggle Button and Enhanced the Hero section

### PR DESCRIPTION
**Pull request by anish2210**
---

# Added a theme toggle button and worked on the hero section to improve the User Interfece.

Previously the Eth and the Solana logos were making it difficult to read the content of the hero section, I used glass morphism to tackle the issue of readability and additionally, I added a button to toggle the theme which is fully responsive. 

image

## 🛠️ Type of Change

- [x] 🐛 Bug fix
- [x] ✨ New feature

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.
- [x] **Warnings:** My changes introduce no new warnings.

---

### CODE REVIEW

**Comment by cb7chaitanya** [comment]
It is just a button right? It would be great if you can add the functionality behind it @anish2210

**Comment by anish2210** [comment]
yeah am already on it @cb7chaitanya

**Comment by anish2210** [comment]
What about the hero section edit, is it acceptable ?

**Review by Rudra-Sankha-Sinhamahapatra — CHANGES_REQUESTED** [review]
Your lint checks have been failed
It would be great if you fix these lint errors

**Comment by anish2210** [comment]
@Rudra-Sankha-Sinhamahapatra I resolved the linting error but now it shows:

image

what should I do?

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
You have merge conflicts try to fix them
@anish2210

**Review by Rudra-Sankha-Sinhamahapatra — COMMENTED** [review]
And also run npm run lint to ensure you dont have any lint errors locally

**Comment by anish2210** [comment]
I am still getting conflicts even if all my branches are up to date ..... i dont think i can get out of it instead I should raise a new PR.

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@anish2210 please make a new pr 
but you need to ensure that you have pulled all the changes here locally using git pull command 
do some research on that 
or just separate those files which you are changing here 
then do git pull

**Comment by anish2210** [comment]
Okkh I'll look into it .... Can you please clear one of my doubt .

Just correct me if I'm wrong: 
I need to make changes in the UI of the Website so ill fork the repo to make a copy, I will create a new branch with my name where I can make changes, while contribution I will git pull from the main branch [or dev branch or dev-frontend branch (confusion)] if any changes are made by the maintainers, then need to git push to my newly created branch and finally raise a pr to merge to the dev-frontend branch.

**Pull request closed without merging**
