### PR TITLE
feat: added top loader for the website

### PR DESCRIPTION
**Pull request by abhinaisai2002**
---

# Pull Request Title

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Number:** Fixes # (issue number)

## 🛠️ Type of Change

- [ ] 🐛 Bug fix
- [x] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.
- [x] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [x] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [ ] **Passes Locally:** All new and existing unit tests pass on my local machine.

---
I have tried building locally, the build is success

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Review by Rudra-Sankha-Sinhamahapatra — CHANGES_REQUESTED** [review]
Your code has branch merge conflicts so please get rid of these conflicts and then re open the PR
And please make sure to provide screenshots or videos whenever you are creating a PR

**Review by Rudra-Sankha-Sinhamahapatra — CHANGES_REQUESTED** [review]
maybe someone fixed this .. @abhinaisai2002 
If it is already done @cb7chaitanya please close this pr

**Comment by Ameerjafar** [comment]
@abhinaisai2002 your branch has  conflicts

**Review by ghost — CHANGES_REQUESTED** [review]
@abhinaisai2002  i think this feature has been added.If not then fix your merge conflicts and reopen the pull request.

**Pull request closed without merging**
