### PR TITLE
wallet page corrections

### PR DESCRIPTION
**Pull request by mukeshblackhat**
Wallet page improvement as per discussion

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Please provide screenshots or screenrecordings

**Comment by mukeshblackhat** [comment]
Screenshot 2024-08-30 at 9 59 58 AM

https://www.loom.com/share/b646d59890f2411a9d99db7f091848d9?sid=1ff71fbc-0448-4304-8144-c0f046b233bc

**Review by ghost — CHANGES_REQUESTED** [review]
@mukeshblackhat the appbar margins and paddings should be adjusted. Adjust it by adding some margins on x axis by mx and give some margins on y axis by my 
Baaki what your thoughts @cb7chaitanya @axatbhardwaj , the sidebar is fine ?

**Comment by cb7chaitanya** [comment]
I am merging this, but there are some UI improvements I would list out in an issue shortly, if you want to pick up that too @mukeshblackhat

**Comment by mukeshblackhat** [comment]
> I am merging this, but there are some UI improvements I would list out in an issue shortly, if you want to pick up that too @mukeshblackhat

sure

**Pull request merged**
