### PR TITLE
Added prisma postinstall generate command 

### LINKED ISSUE #21: Add Prisma Postinstall Command
Summary:
Automate Prisma Client generation by adding prisma generate to the postinstall script in package.json. This will ensure the client is always up to date after dependencies are installed.

Current Behavior:
Manual prisma generate is required after installing dependencies.

Expected Behavior:
Prisma Client is automatically regenerated after npm install or yarn install.

Solution:
Add prisma generate to the postinstall script in package.json.

Note
For more details on Prisma Client generation, refer to the [Prisma documentation](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/generating-prisma-client).

image

### PR DESCRIPTION
**Pull request by Riya267**
###
---

# Pull Request Title - Automate Prisma Client Generation with Postinstall Script

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Number:** Fixes #21

## 🛠️ Type of Change

- [ ] 🐛 Bug fix
- [x] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.
- [x] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [x] **Documentation:** I’ve updated the documentation to reflect my changes.
- [x] **Warnings:** My changes introduce no new warnings.
- [x] **Tests:** I’ve added tests to verify that my changes work as expected.
- [x] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

## Description
This pull request adds the prisma generate command to the postinstall script in package.json. This change ensures that the Prisma Client is automatically regenerated after installing dependencies, which helps keep the client in sync with the Prisma schema and avoids potential inconsistencies.

Note: As recommended in the Prisma documentation, keeping both the prisma and @prisma/client packages in sync is crucial to avoid unexpected errors or behaviors.

image

### CODE REVIEW

**Comment by maniksharma17** [comment]
Hey, is it a good idea to add `npx prisma generate` in dev and build commands to automate the process without a new script?

**Comment by Parikshit2001** [comment]
No, what she did is right only,`postinstall` script is needed when you're hosting the app.
It gives error when you deploy it and you don't have the `postinstall` script.

**Comment by Riya267** [comment]
> Hey, is it a good idea to add `npx prisma generate` in dev and build commands to automate the process without a new script?

Adding npx prisma generate to the dev and build commands can automate Prisma Client generation, which is great for local development since it ensures the client is always up to date and reduces manual steps.

However, in production, this might add unnecessary overhead. Prisma Client is typically generated during the CI/CD build step, so running it again at runtime isn't needed and can slow things down.

Also, Prisma's [Vercel deployment guide](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-vercel) mentions that using prisma generate in the postinstall hook ensures the client is available in node_modules/@prisma/client, which is important because Vercel caches node_modules.

**Comment by cb7chaitanya** [comment]
Sounds good

**Pull request merged**
