### PR TITLE
Sign out button code fix

### PR DESCRIPTION
**Pull request by iSouvikKhan**
---

# Sign Out button correction

Have added signOut method in 2 sign out buttons
on home screen, have conditionally made the "Signout with Google" button visible or hidden

**Issue Number:** Fixes # (issue number)

## 🛠️ Type of Change

- [x] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.
- [ ] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [x] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [x] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Comment by iSouvikKhan** [comment]
Hi @cb7chaitanya, there were no particular issue for this PR, while going through the code I found signout button is not working, that I have corrected in this PR.

Thanks

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Can you provide video before and after changes @iSouvikKhan

**Comment by dyaipayan22** [comment]
@iSouvikKhan I have already fixed it in #57

**Comment by cb7chaitanya** [comment]
https://github.com/user-attachments/assets/876645eb-4e53-41f3-8a7d-e63088bf3f8b

Already works

**Review by Rudra-Sankha-Sinhamahapatra — COMMENTED** [review]
@iSouvikKhan it is already working you can close the issue for now ,thanks

**Comment by iSouvikKhan** [comment]
Sure @Rudra-Sankha-Sinhamahapatra 

Thanks

**Pull request closed without merging**
