### PR TITLE
[FEAT]:QR code receive functionality added

### LINKED ISSUE #202: [FEAT] Create an interface to support recieving SOL in the tiplink wallet
- We are supporting 2 options to get public key when clicking on recieve button within the wallet interface
- First option should be getting public key of the user via QR code
- Second option would be getting the public key in plain text to copy

For reference, check out Phantom's Interface

### PR DESCRIPTION
**Pull request by Rudra-Sankha-Sinhamahapatra**
---

# Pull Request Title

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Number:** Fixes #202 

## 🛠️ Type of Change

- [ ] 🐛 Bug fix
- [x] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.
- [x] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [x] **Warnings:** My changes introduce no new warnings.
- [x] **Tests:** I’ve added tests to verify that my changes work as expected.
- [x] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

I have added a QR code generation of the publicKey of the user available on the db 

Here's a breif of it 

https://github.com/user-attachments/assets/549ed1e7-fa1a-407b-be5d-ebc8599eb980

### CODE REVIEW

**Comment by cb7chaitanya** [comment]
Is scanning this QR code actually spitting out the user's public key?

**Comment by cb7chaitanya** [comment]
Also I would appreciate if you keep the receive tab's code in a dedicated component, and render it conditionally depending on what option is selected within our interface because we have other options we have to provide for which we would have to create seperate components too

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Haan after scanning the QR code it shows the public key which is in the db 
And yes whenever we click the recieve then only this pops up 
And when we click other options like send and all it does not do anything 
@cb7chaitanya

**Comment by cb7chaitanya** [comment]
Ok but if we can keep components specific to options we are providing, that would be appreciated

Because otherwise walletDetail component would look too cluttered

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@cb7chaitanya done see i have made it in separate component 

WhatsApp Image 2024-10-04 at 17 22 27_37187cf4

image

see my db  publicKey is in the qr .. you can scan the qr to be sure

**Comment by cb7chaitanya** [comment]
Works, good work @Rudra-Sankha-Sinhamahapatra

**Pull request merged**
