### PR TITLE
Enhance user interface to differentiate from TipLinks

### LINKED ISSUE #23: Improve the UI to our own better version, different from the TipLinks UI.
**This PR aims to enhance our user interface by differentiating it from the TipLinks UI and creating a better version. The changes include:**

- Redesigning the layout for a more user-friendly and mono-chromatic look.
- Updating color schemes.
- Adding new visual elements for improved aesthetics
- Optimizing the interface for better performance and responsiveness

**Changes:**

1. **Layout Improvements:**
    - Redesigned the main layout to be more intuitive and visually appealing.
    - Removed elements that were directly copied from TipLinks.
2. **Color Schemes:**
    - Introduced a new color palette that aligns with our brand identity.
3. **Visual Enhancements:**
    - Added new icons and images to enhance the visual appeal.
    - Improved spacing and alignment for a cleaner appearance.
4. **Performance Optimization:**
    - Refactored CSS and JavaScript for better performance.
    - Ensured that the UI is responsive across different devices and screen sizes.

**Screenshots:**

**Before:**

image

**After:**

image

**Before:**

image

**After:**

image

**Before:**

image

**After:**

image

**Testing:**

- [x]  Verified that the new UI works well on different browsers (Chrome, Firefox, Safari)
- [x]  Tested responsiveness on mobile and tablet devices
- [x]  Confirmed that all existing functionality remains intact

**Additional Notes:**

- Please review the new design and provide feedback. If you are okay with it, I will start making changes according to feedback and complete the UI.

@cb7chaitanya

### PR DESCRIPTION
**Pull request by Pawank06**
---

**Issue Number:** Fixes #23 

# Enhance user interface to differentiate from TipLinks UI

This PR aims to enhance our user interface by differentiating it from the TipLinks UI and creating a better version. The changes include:
- Updated color scheme to improve visual appeal.
- Redesigned navigation bar for better usability.
- Improved button styles for consistency.
- Refined typography for better readability.
- Added new icons to enhance user experience.

## Demo:

https://github.com/user-attachments/assets/32a5510c-4678-482e-a502-987e65eb48f1

## 🛠️ Type of Change

- [ ] 🐛 Bug fix
- [x] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.
- [ ] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [ ] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [ ] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Comment by Praashh** [comment]
> # Enhance user interface to differentiate from TipLinks
> This PR aims to enhance our user interface by differentiating it from the TipLinks UI and creating a better version. The changes include:
> 
> * Updated color scheme to improve visual appeal.
> * Redesigned navigation bar for better usability.
> * Improved button styles for consistency.
> * Refined typography for better readability.
> * Added new icons to enhance user experience.
> 
> **Issue Number:** Fixes #23
> 
> ## 🛠️ Type of Change
> * [ ]  🐛 Bug fix
> * [x]  ✨ New feature
> * [ ]  🚨 Breaking change
> * [ ]  📚 Documentation update
> 
> ## ✅ Checklist
> To ensure a smooth review process, please check off each item as you complete it:
> 
> * [x]  **Code Style:** My code adheres to the project’s style guidelines.
> * [x]  **Self-Review:** I have reviewed my own code and made improvements.
> * [ ]  **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
> * [ ]  **Documentation:** I’ve updated the documentation to reflect my changes.
> * [ ]  **Warnings:** My changes introduce no new warnings.
> * [ ]  **Tests:** I’ve added tests to verify that my changes work as expected.
> * [ ]  **Passes Locally:** All new and existing unit tests pass on my local machine.
> 
> We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

Can you attach any image-file of your UI-related changes?

**Comment by Pawank06** [comment]
> > # Enhance user interface to differentiate from TipLinks
> > This PR aims to enhance our user interface by differentiating it from the TipLinks UI and creating a better version. The changes include:
> > 
> > * Updated color scheme to improve visual appeal.
> > * Redesigned navigation bar for better usability.
> > * Improved button styles for consistency.
> > * Refined typography for better readability.
> > * Added new icons to enhance user experience.
> > 
> > **Issue Number:** Fixes #23
> > ## 🛠️ Type of Change
> > 
> > * [ ]   🐛 Bug fix
> > * [x]   ✨ New feature
> > * [ ]   🚨 Breaking change
> > * [ ]   📚 Documentation update
> > 
> > ## ✅ Checklist
> > To ensure a smooth review process, please check off each item as you complete it:
> > 
> > * [x]   **Code Style:** My code adheres to the project’s style guidelines.
> > * [x]   **Self-Review:** I have reviewed my own code and made improvements.
> > * [ ]   **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
> > * [ ]   **Documentation:** I’ve updated the documentation to reflect my changes.
> > * [ ]   **Warnings:** My changes introduce no new warnings.
> > * [ ]   **Tests:** I’ve added tests to verify that my changes work as expected.
> > * [ ]   **Passes Locally:** All new and existing unit tests pass on my local machine.
> > 
> > We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.
> 
> Can you attach any image-file of your UI-related changes?

https://github.com/code100x/tiplink/issues/23 check it out.

**Comment by cb7chaitanya** [comment]
Great job man, UI looks pretty good @Pawank06

**Comment by Pawank06** [comment]
> Great job man, UI looks pretty good @Pawank06 

Thank you Ser, Going to add some more changes to it.

Todo - 

- Refactor the code.
- Add images to the feature cards.
- Change the text.

**Pull request merged**
