### PR TITLE
[FIX] Auth

### LINKED ISSUE #24: Login with Google Button not working
For me "login with Google" button is not working
Someone please comment down below if its working for you,
do comment down and let me know if it is not working also

### PR DESCRIPTION
**Pull request by Prakash-Raut**
---

# FIX : Auth

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Number:** Fixes #24 

## 🛠️ Type of Change

- [✅] 🐛 Bug fix
- [ ] ✨ New feature
- [✅] 🚨 Breaking change
- [ ] 📚 Documentation update

## Approach
Removed the old dependecies (@next-auth/prisma-adapter, next-auth) and added next-auth-beta

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [✅] **Code Style:** My code adheres to the project’s style guidelines.
- [✅ ] **Self-Review:** I have reviewed my own code and made improvements.
- [ ] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [✅] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [ ] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

### CODE REVIEW

**Comment by cb7chaitanya** [comment]
Have you tested it and also why did you remove the auth options part?
Also edited the env.sample

**Comment by Prakash-Raut** [comment]
Auth Flow Video Link - https://www.loom.com/share/084b7d7624294eeeaf66d00407f943c8?sid=355037d1-45a0-4113-9b41-b7391347ed2d

**Review by Rudra-Sankha-Sinhamahapatra — CHANGES_REQUESTED** [review]
@Prakash-Raut 
First of all you have merge conflicts 
You have restructured .env.sample which is not ideal ..we should not change it.It will only be edited by the maintainers

Now when it comes to auth issue refer to issue #24 there @Praashh has explained its working ...

Thank you

**Review by ghost — CHANGES_REQUESTED** [review]
@Prakash-Raut its not needed now,everything works fine
Thanks for your contribution
You can close this PR @cb7chaitanya

**Comment by Prakash-Raut** [comment]
Closed

**Pull request closed without merging**
