### PR TITLE
feat:beautify home page

### PR DESCRIPTION
**Pull request by Praashh**
image

### CODE REVIEW

**Comment by Praashh** [comment]
https://github.com/user-attachments/assets/a92f1ecf-b71b-4c3e-855d-e8d4f027a8dc

as of now, we have this basic landing page, will be adding more section into it. Working on it

**Comment by cb7chaitanya** [comment]
Cool stuff, we need to keep the UI pretty similar to what tiplink's actual website is, so fair dues

**Comment by cb7chaitanya** [comment]
Is it responsive @Praashh ?

**Comment by Praashh** [comment]
> Is it responsive @Praashh ?

100% ser

**Comment by vanshavenger** [comment]
BTW are we using Shadcn here?
as i see components.json file but globals.css don;t have its colours 

Also @Praashh @cb7chaitanya can we add NextJs top Loader to make it more better ?
I was thinking to do that but ig @Praashh can do that in this PR only

**Comment by Praashh** [comment]
> BTW are we using Shadcn here? as i see components.json file but globals.css don;t have its colours
> 
> Also @Praashh @cb7chaitanya can we add NextJs top Loader to make it more better ? I was thinking to do that but ig @Praashh can do that in this PR only

yes ser we are using shadCN and loader as well. if you think something that you can do please create a issue and let cb7chaitanya know and start working..

**Comment by Ameerjafar** [comment]
@Praashh  can i do the wallet page if you haven't done yet.

**Comment by Praashh** [comment]
> @Praashh can i do the wallet page if you haven't done yet.

let me quickly do the home page, you can pick it up afterwards.

**Comment by Ameerjafar** [comment]
waiting for your pr @Praashh

**Comment by KushalBhanot** [comment]
I can help with the side menu or any other UI element/feature. Let me know @cb7chaitanya and @Praashh  if I can pick it up.

**Comment by Praashh** [comment]
> waiting for your pr @Praashh

Hey, it's done,  I will push by EOD.

https://github.com/user-attachments/assets/6e5ed911-538b-4129-a7b9-23fa36b03a4e

**Comment by Praashh** [comment]
> I can help with the side menu or any other UI element/feature. Let me know @cb7chaitanya and @Praashh if I can pick it up.

awesome, let's have basic UI first then after you can do it.

**Comment by Ameerjafar** [comment]
@Praashh working on wallet page frontend

**Pull request merged**
