### PR TITLE
fix-walletPage-login-ui

### LINKED ISSUE #146: [BUGFIX] Fix this
Screenshot (95)

- This should be the same as the dropdown on the landing page, please fix this

### PR DESCRIPTION
**Pull request by saketsingh0078**
**Issue Number:** Fixes #146 

## 🛠️ Type of Change

- [x] 🐛 Bug fix

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x] **Code Style:** My code adheres to the project’s style guidelines.
- [x] **Self-Review:** I have reviewed my own code and made improvements.

https://github.com/user-attachments/assets/6adebb3b-ae33-4040-9db8-3a6581898faa

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Looks good

**Comment by cb7chaitanya** [comment]
On reload, the bug gets worse, please solve that

**Comment by saketsingh0078** [comment]
@cb7chaitanya  u can check u now. 

https://github.com/user-attachments/assets/8ef2dfcb-a2cf-4f03-ade3-3d83eea032c2

**Comment by cb7chaitanya** [comment]
Looks fine, merging it

**Pull request merged**
