### PR TITLE
added google auth to home component

### PR DESCRIPTION
**Pull request by PoulavBhowmick03**
---

# Pull Request Title

Added the Google sign in functionality to the Home component button
image

## 🛠️ Type of Change

- [ ] 🐛 Bug fix
- [X] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [X] **Code Style:** My code adheres to the project’s style guidelines.
- [X] **Self-Review:** I have reviewed my own code and made improvements.
- [ ] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [ ] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [X] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Comment by PoulavBhowmick03** [comment]
@cb7chaitanya gm, i was going through the repo on what can be worked on, and found this, would love to contribute more, can we discuss on the potential features that can be implemented?

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@PoulavBhowmick03 can you provide screenshots or videos
thanks for your contribution

**Comment by PoulavBhowmick03** [comment]
> @PoulavBhowmick03 can you provide screenshots or videos thanks for your contribution
Sure

https://github.com/user-attachments/assets/0cdfdf8f-13b7-49c9-b6f1-9dcecbc4a9bf

**Review by Rudra-Sankha-Sinhamahapatra — CHANGES_REQUESTED** [review]
even after signin its showing sign in with google , change this to something like 
Continue to Dashboard or Continue to Wallet @PoulavBhowmick03

**Review by Rudra-Sankha-Sinhamahapatra — CHANGES_REQUESTED** [review]
and please dont create pr on main branch there are other branches to create this pr...
Please close this PR and re open this to the suitable branch

**Comment by PoulavBhowmick03** [comment]
Okay. Sure

**Pull request closed without merging**
