### PR TITLE
Fixed the Sign up with Google button not working

### PR DESCRIPTION
**Pull request by Parikshit2001**
---

# Pull Request Title

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Number:** Fixes # (issue number)

## 🛠️ Type of Change

- [ ] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [ ] **Code Style:** My code adheres to the project’s style guidelines.
- [ ] **Self-Review:** I have reviewed my own code and made improvements.
- [ ] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [ ] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [ ] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Review by Rudra-Sankha-Sinhamahapatra — COMMENTED** [review]
Please provide the screenshot or video of  your changes @Parikshit2001

**Review by Rudra-Sankha-Sinhamahapatra — COMMENTED** [review]
Someone already raised a PR .Refer to this PR #102     @Parikshit2001

**Review by Rudra-Sankha-Sinhamahapatra — CHANGES_REQUESTED** [review]
sign up works though maybe .. @abhinaisai2002
can you provide videos or screenshots

@cb7chaitanya check this,maybe the issue dosent exists

**Comment by Parikshit2001** [comment]
Someone already raised a PR .Refer to this PR https://github.com/code100x/tiplink/pull/102

**Pull request closed without merging**
