### PR TITLE
[FIX]-WALLET-PAGE

### LINKED ISSUE #98: Implement User Wallet Page.
### **Title**: Create User Wallet Page

**Description**:
- Implement the User Wallet page in the application.
- Ensure that the design and layout follow the provided Figma design.

**Tasks**:
1. Create the User Wallet page.
2. Implement UI components based on the design.
3. Ensure responsiveness and cross-browser compatibility.

**Demo**: 

MacBook Air - 1(9)

**Acceptance Criteria**:
- The User Wallet page is functional and visually aligns with the design.
- The page is fully responsive.

**Priority**: Medium/High

**Assignee**: I'm working on it.

### PR DESCRIPTION
**Pull request by devansh193**
https://github.com/user-attachments/assets/c7d8a46e-33f0-427e-b216-9db9748ae1fa

##FIXES
1. The AppBar is configured to allow users to connect and disconnect their wallet only after they have successfully logged in.
2. The Wallet page is constructed using reusable components, ensuring modularity and maintainability. 
3. Minor UI adjustments have been implemented.

---

# Pull Request Title

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Number:** Fixes #98 

## 🛠️ Type of Change

- [ x] 🐛 Bug fix
- [ ] ✨ New feature
- [x ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [x ] **Code Style:** My code adheres to the project’s style guidelines.
- [x ] **Self-Review:** I have reviewed my own code and made improvements.
- [ ] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [ ] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [ ] **Passes Locally:** All new and existing unit tests pass on my local machine.

---
We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Comment by devansh193** [comment]
@cb7chaitanya  Please Review!

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@devansh193 I think for the issue #98 someone is already working and 1 PR has been merged

**Comment by devansh193** [comment]
@Rudra-Sankha-Sinhamahapatra   i noticed that the recently merged pull request contained several hard-coded elements and the related issue remains unresolved. So I took the initiative to fix the outstanding issues and reduce the hard-coded elements. If the issue is still open and needs further attention, I would appreciate if it could be assigned to me.

**Comment by cb7chaitanya** [comment]
We are creating a new Tiplink wallet itself on Google Sign In, not connecting to existing solana wallets
Please visit https://tiplink.io/ for reference

**Comment by cb7chaitanya** [comment]
Try to understand the flow o what is being done, what is the point of connecting an already existing solana wallet to our frontend 
Tiplink does something entirely different, If you want to understand how are we implementing this, refer to the notion doc in Readme

**Comment by devansh193** [comment]
@cb7chaitanya  I appreciate your explanation and apologize for any inconvenience caused.

**Comment by devansh193** [comment]
@cb7chaitanya I appreciate your explanation and apologize for any inconvenience caused.

**Pull request closed without merging**
