### PR TITLE
Added .husyk 

### PR DESCRIPTION
**Pull request by ArpitBlagan**
---

# Pull Request Title added husky

Thank you for contributing to our project! Please provide a summary of your changes and reference any related issues below.

**Issue Number:** Fixes # (issue number)

## 🛠️ Type of Change

- [ ] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 🚨 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist

To ensure a smooth review process, please check off each item as you complete it:

- [✅] **Code Style:** My code adheres to the project’s style guidelines.
- [✅] **Self-Review:** I have reviewed my own code and made improvements.
- [ ] **Comments:** I’ve added comments to explain complex or non-obvious parts of the code.
- [ ] **Documentation:** I’ve updated the documentation to reflect my changes.
- [ ] **Warnings:** My changes introduce no new warnings.
- [ ] **Tests:** I’ve added tests to verify that my changes work as expected.
- [✅] **Passes Locally:** All new and existing unit tests pass on my local machine.

---

We appreciate your contributions! If you have any questions or need further assistance, feel free to reach out.

### CODE REVIEW

**Review by Rudra-Sankha-Sinhamahapatra — CHANGES_REQUESTED** [review]
@ArpitBlagan can you provide screenshots of the working on husky or a video

**Comment by cb7chaitanya** [comment]
Can you resolve these conflicts, would merge it then @ArpitBlagan

**Comment by ArpitBlagan** [comment]
Done @cb7chaitanya

**Comment by ArpitBlagan** [comment]
> @ArpitBlagan can you provide screenshots of the working on husky or a video

Screenshot 2024-08-09 at 8 46 59 AM

**Pull request merged**
